import axios from "axios";

export const $api2 = axios.create({baseURL: '/api/',});
<DataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataView>


<DataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataView>
<DataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataView>
<DataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataView>
<DataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataView>
<DataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataView>
<DataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataView>
<DataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataView>
<DataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataView>
<DataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataViewDataView>